# Generated by Django 4.2.7 on 2026-01-23 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='题目名称')),
                ('description', models.TextField(verbose_name='题目描述')),
                ('requirements', models.TextField(blank=True, verbose_name='选题要求')),
                ('max_students', models.PositiveIntegerField(default=1, verbose_name='最大可选人数')),
                ('current_count', models.PositiveIntegerField(default=0, verbose_name='当前已选人数')),
                ('status', models.IntegerField(choices=[(1, '开放选题'), (2, '名额已满'), (3, '已关闭')], default=1, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to=settings.AUTH_USER_MODEL, verbose_name='指导教师')),
            ],
            options={
                'verbose_name': '论文题目',
                'verbose_name_plural': '论文题目',
                'db_table': 'topic',
                'ordering': ['-created_at'],
            },
        ),
    ]
