# Generated by Django 4.2.7 on 2026-01-23 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, '待审批'), (2, '已通过'), (3, '已拒绝')], default=1, verbose_name='状态')),
                ('student_reason', models.TextField(blank=True, verbose_name='申请理由')),
                ('teacher_comment', models.TextField(blank=True, verbose_name='审批意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to=settings.AUTH_USER_MODEL, verbose_name='学生')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='topics.topic', verbose_name='论文题目')),
            ],
            options={
                'verbose_name': '选题记录',
                'verbose_name_plural': '选题记录',
                'db_table': 'selection',
                'ordering': ['-created_at'],
                'unique_together': {('student', 'topic')},
            },
        ),
    ]
